[package]
name = "sp1-recursion-circuit"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
slop-alloc = { workspace = true }
slop-air = { workspace = true }
slop-koala-bear = { workspace = true }
slop-bn254 = { workspace = true }
slop-jagged = { workspace = true }
slop-commit = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-basefold = { workspace = true }
slop-basefold-prover = { workspace = true }
slop-symmetric = { workspace = true }
slop-algebra = { workspace = true }
slop-multilinear = { workspace = true }
slop-sumcheck = { workspace = true }
slop-matrix = { workspace = true }
slop-stacked = { workspace = true }
slop-challenger = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-hypercube = { workspace = true }
sp1-derive = { workspace = true }
sp1-recursion-compiler = { workspace = true }
sp1-recursion-machine = { workspace = true }
sp1-recursion-executor = { workspace = true, features = ["program_validation"] }
sp1-primitives = { workspace = true }
slop-tensor = { workspace = true }
slop-whir = { workspace = true }
tokio = { workspace = true }

itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = "0.8.5"
tracing = { workspace = true }
rayon = "1.10.0"

[dev-dependencies]
sp1-core-executor = { workspace = true }
sp1-hypercube = { workspace = true, features = ["test-proof"] }
sp1-recursion-machine = { workspace = true }
sp1-recursion-gnark-ffi = { workspace = true }
slop-dft = { workspace = true }
zkhash = "0.2.0"
rand = "0.8.5"
futures = "0.3.31"
test-artifacts = { workspace = true }
bincode = "1.3.3"

[features]
# Enables debug features in dependencies.
debug = ["sp1-core-machine/debug", "sp1-recursion-compiler/debug"]

[lints]
workspace = true
