imports_granularity = "Crate"
use_small_heuristics = "Max"
wrap_comments = true
comment_width = 100
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
