[package]
name = "u256x2048-mul-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8"
num = { version = "0.4.1" }
sp1-zkvm = { workspace = true }
sp1-derive = { path = "../../../crates/derive" }
bytemuck = "1.15.0"
