[package]
name = "slop-multilinear"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-alloc = { workspace = true }
slop-tensor = { workspace = true }
slop-futures = { workspace = true }
slop-commit = { workspace = true }
# slop-baby-bear = { workspace = true }

slop-algebra = { workspace = true }
slop-matrix = { workspace = true }
slop-challenger = { workspace = true }

serde = { workspace = true }
rayon = { workspace = true }
derive-where = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }

[dev-dependencies]
slop-baby-bear = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
