[package]
name = "slop-keccak-air"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-keccak-air = {workspace = true}

[lints]
workspace = true
