[package]
name = "slop-poseidon2"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-poseidon2 = { workspace = true }
