[package]
version = "0.1.0"
name = "rsp-script"
edition = "2021"

[dependencies]
alloy-primitives = "0.8.5"
bincode = "1.3.3"
clap = { version = "4.5.7", features = ["derive", "env"] }
tokio = "1.42.0"
tracing = "0.1"
# rsp
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "3647076" }

# sp1
sp1-prover = { path = "../../../crates/prover" }
sp1-sdk = { workspace = true }

sp1-core-executor = { workspace = true, features = ["profiling"] }
sp1-build = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-primitives = { workspace = true }

[build-dependencies]
sp1-build = { path = "../../../crates/build" }

[features]
default = []

[[bin]]
name = "core_u64"
path = "bin/core_u64.rs"
