[package]
name = "bls12_381_tests"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
sp1-sdk = { workspace = true }
sp1-core-executor = { workspace = true }
rand = { workspace = true }
sp1-test = { workspace = true }
tokio = { workspace = true }
color-eyre = { workspace = true }

# note: we use the patched version (which should be mostly equivalent to the original, outside the vm)
# because we want to test the field ops which are not exposed in the original
bls12_381-patched = { workspace = true }
group = "0.13.0"

[features]
prove = []
gpu = ["sp1-sdk/cuda"]


[build-dependencies]
sp1-build = { workspace = true }
