[package]
name = "slop-dft"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-alloc = { workspace = true }
slop-tensor = { workspace = true }
slop-algebra = { workspace = true }
slop-matrix = { workspace = true }

p3-dft = { workspace = true }

serde = { workspace = true }
