[package]
name = "slop-whir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
slop-algebra = { workspace = true }
slop-basefold = {workspace = true}
slop-multilinear = { workspace = true }
slop-challenger = { workspace = true }
slop-utils = { workspace = true }
slop-commit = { workspace = true }
slop-matrix = { workspace = true }
slop-tensor = { workspace = true }
slop-alloc = { workspace = true }
slop-baby-bear = { workspace = true }
slop-dft = { workspace = true }
slop-koala-bear = { workspace = true }
slop-symmetric = { workspace = true }
slop-merkle-tree = { workspace = true }
slop-bn254 = { workspace = true }

rand = "0.8.5"
thiserror = "1.0"
itertools = "0.12.0"
serde = { version = "1.0.207", features = ["derive"] }
derive-where = { workspace = true }
tokio = { workspace = true }
rayon = {workspace = true}

[dev-dependencies]
slop-baby-bear = { workspace = true }
bincode = "1.3.3"
tracing = { workspace = true }
