[package]
name = "cycle-tracking-program"
version = "1.1.0"
edition = "2021"
publish = false

[[bin]]
name = "normal"
path = "bin/normal.rs"

[[bin]]
name = "report"
path = "bin/report.rs"

[dependencies]
sp1-zkvm = { workspace = true }
sp1-derive = { path = "../../../crates/derive" }
